apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  type: NodePort
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
